### ISSUE TITLE
OpenCL extension 'cl_khr_fp64' is unsupported

### ISSUE THREAD

**Issue by tengfeisun2018** [fangq/mcxcl#24]
Building kernel with option: -cl-mad-enable -DMCX_USE_NATIVE -DMCX_SIMPLIFY_BRANCH -DMCX_VECTOR_INDEX -DMCX_SRC_PENCIL  -DMCX_SAVE_DETECTORS -DMCX_DO_REFLECTION
Kernel build log:
:161:26: error: OpenCL extension 'cl_khr_fp64' is unsupported
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
                         ^

error: front end compiler failed build.

MCXCL ERROR(11):Error: Failed to build program executable! in unit mcx_host.cpp:506

**Comment by 3upperm2n** [comment]
tenfeisun2018, you can use **_clinfo_** to check whether your device support cl_khr_fp64.

**Comment by fangq** [comment]
@tengfeisun2018, can you print the device info using "mcxcl -L"? what driver are you using?

**Comment by fangq** [comment]
I am going to close this issue as there is no update.

**Comment by zanklanecek** [comment]
I am having the same error on the newest MMC-CL.
Is there a way to enable cl_khr_fp64? It has something to do with following line:
`#pragma OPENCL EXTENSION cl_khr_fp64 : enable`
but I am not sure where to put it.

Is there a repo to open Issues for MMC-OpenCl version?

Error:

```
2:298:26: error: OpenCL extension 'cl_khr_fp64' is unsupported

MMCLAB ERROR (11): Error: Failed to build program executable! in unit mmc_cl_host.c:291
```

**Comment by fangq** [comment]
what hardware are you using? cl_khr_fp64 is typically supported by most newer cpus/gpus. if it is not supported, likely either your opencl library or driver was not installed properly.

similarly, can you run 

`mmcl -L`

to see what the output?

**Comment by fangq** [comment]
regarding repos, you can just open mmc issue

https://github.com/fangq/mmc/issues

mmcl will be merged to mmc in the next major release (v2.0). the binary will be named as mmc (that supports both SSE and opencl, and cuda in the future, options)

**Comment by zanklanecek** [comment]
It probably has to do with older hardware/software (image below). I updated both Intel and Nvidia graphics drivers. It is working fine on my newer laptop with Intel-8 series. 
However there is a problem with output on MMC-CL (strange 4x4x5 struct field in matlab). I will open an issue in mmc/issues.

![image](https://user-images.githubusercontent.com/24533740/61297907-873c5580-a7dd-11e9-9a7b-9faa1055ef9f.png)

**Comment by fangq** [comment]
yes, intel's opencl run times does not support 4-th gen cpu on windows

https://software.intel.com/en-us/node/540387
