### ISSUE TITLE
MCXCL ERROR(1001):Unknown in unit mcx_host.cpp:243

### ISSUE THREAD

**Issue by naitsok** [fangq/mcxcl#52]
Hello,
I'm trying to run the example script in MATLAB from MCXLAB-CL: demo_mcxlab_basic.m but get the error
MCXCL ERROR(1001):Unknown in unit mcx_host.cpp:243
The same error appears when I run mcxcl -L in terminal.

PC configuration:
1) No GPU
2) AMD Epyc processor × 32 
3) Rocky Linux 8.9
4) Graphics llvmpipe (LLVM 16.0.6, 256 bits) (no descrete GPU)
5) MCXStudio 2024.2

What I've tried:
1) Recompile MCXCL from source. Recompile worked but still the same error when running mcxcl -L.
2) Checked docs about installation but there is not so much about AMD processors.
3) Tried to search this error in issues and internet, but not much found.

What should I do to solve the issue? Is it related to my harware setup and incorrect libraries? Or maybe something else?
Thank you!

**Comment by fangq** [comment]
make sure you have opencl runtime installed. on Linux, you need to install pocl

http://portablecl.org/docs/html/install.html
