### ISSUE TITLE
Cannot run JSON file obtained by mcx2json() function

### ISSUE THREAD

**Issue by naitsok** [fangq/mcxcl#53]
Hello,

I have the following MATLAB script to produce JSON file:
```matlab
cfg.gpuid = 1;
% cfg.gpuid='11'; % use two GPUs together
cfg.autopilot = 1;
% general simulation settings
cfg.seed = 44113327;
cfg.nphoton = 1e7; % must not exceed this, otherwise MATLAB crashes
% volume configuration
cfg.vol = uint8(ones(80, 80, 100));
cfg.prop = [ ...
    0 0 1 1; ...
    0 4 0.6 1.33 ...
    ];
% source configuration
cfg.srcpos = [40 40 0];
cfg.srcdir = [0 0 1];
cfg.srctype = 'disk';
cfg.srcparam1 = [ ...
    35 0 0 0 ... % radius of disk is 35 grid units (= mm in this case)
    ];
% timing settings
cfg.tstart = 0;
cfg.tend = 10e-9;
cfg.tstep = 10e-9;
% length parameter configuration
cfg.unitinmm = 1.0; % one voxel edge size is 1 mm
% boundary condition configuration
cfg.isreflect = 0;
% last 6 numbers indicate that we keep photons escaping from each boundary
cfg.bc = '______111111';
% save data of detected photons
cfg.issaveexit = 1;
% show progress bar and save photon paths
cfg.debuglevel = 'MP';
% nubmer of positions for trajectories to store
cfg.maxjumpdebug = 1e10;

mcx2json(cfg, ['simulation_' char(datetime('now', 'Format', 'yyyy-MM-dd_HH-mm-ss'))]);
```
However when I the run `./mcxcl -f /data/Projects/AOT/MC/AOTSimulator/simulation_2024-06-04_11-20-20.json`, I get the following error: `free(): double free detected in tcache 2
Aborted (core dumped)
`
What am I doing wrong? I tried to search issues and google group but did not find such an error. The JSON file is also attached.
When I use this cfg structure directly in MATLAB using `mcxlab(cfg)' simulation works. However, when running directly in MATLAB, I have to decrease the number of photons to 1e5, otherwise MATLAB crashed with segmentation fault. But using 1e5 photons kills all the parallelism and makes the simulation extremely slow since I need to do 100 simulations with 1e5 photons at least.
I use the latest MCXCL v2024.2. Thank you.
[simulation_2024-06-04_11-20-20.json](https://github.com/user-attachments/files/15545197/simulation_2024-06-04_11-20-20.json)

**Comment by fangq** [comment]
@naitsok, thanks for reporting this issue. I was able to reproduce it on my side. I fixed it with the above patch.

I've recompiled all nightly build binaries, try redownload it at https://mcx.space/nightly/
