### ISSUE TITLE
--maxjumpdebug still gives the MCXCL ERROR(-2):unknown verbose option in unit mcx_utils.c:3999

### ISSUE THREAD

**Issue by naitsok** [fangq/mcxcl#55]
Thanks for the comprehensive comment! I indeed need to take into account the weight of a photon packet in the analysis.
I've downloaded the latest lightly build, but I still get the same error when running mcxcl -f simulation_2024-06-04_11-20-20.json --debug MP --maxjumpdebug 1e10: MCXCL ERROR(-2):unknown verbose option in unit mcx_utils.c:3999.
Now it seems that the line number is different possibly due to previously made changes.
What am I doing wrong?

thanks for catching this. the missing `--maxjumpdebug` flag has been added.

I also made it possible to accept floating-point numbers, as you wrote, with this flag, but 1e10 will not work. By default, each trajectory position stores 6 floating point numbers, 1e10\*6\*sizeof(float) = 224GB, which can not be stored on most of commercial GPUs. even it can fit, loading/saving/**properly analyzing** such large amount data will be extremely painful.

I highlighted "properly analyzing" - this is because users often intuitively treat each trajectory equally in their data analysis, but in reality, each segment of the path is associated with weight changes, and they must be accounted properly to generate correct statistics. The trajectory data has been labeled as "debugging purpose only"  since the beginning because it is not recommended for analyses.

one more comment: `cfg.maxjumpdebug` is stored as an unsigned integer internally, so it won't get value higher than 2^31-1.

_Originally posted by @fangq in https://github.com/fangq/mcxcl/issues/54#issuecomment-2150419452_

**Comment by fangq** [comment]
please reopen #54 instead of creating a new issue. closing
