### ISSUE TITLE
Allinone zip for Brainstorm

### ISSUE THREAD

**Issue by Edouard2laire** [fangq/mcxcl#59]
Hello @fangq , 

Would it be possible to generate all-in-one zip for Brainstorm the latest version of MCXlab / MCXlabcl as for 
- mcxlab: http://mcx.space/nightly/release/v2020/lite/mcxlab-allinone-x86_64-v2020.zip
- mcxlabcl: http://mcx.space/nightly/release/v2020/lite/mcxlabcl-allinone-x86_64-v2020.zip

so i could update the plugin definition in Brainstorm with the new version supporting arm mac ? 

Thanks a lot
Edouard

**Comment by fangq** [comment]
@Edouard2laire, happy to do that - I remember you previously want to have a zip file that is as small as possible, we deleted mcxfilter.mex* and examples, is this still your preference?

**Comment by Edouard2laire** [comment]
Hello, 

I just tried MCXlabCl on my Mac, and it is working! (minus that error when simulating too many photons)


> please also test these files to see if they run - they are from today's nightly build. the mac mex file does not have upx compression, thus is bigger.

ok, we will see if people from Brainstorm complain.
